<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54277" started-at="2023-02-27T12:32:38Z" finished-at="2023-02-27T12:33:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54277" started-at="2023-02-27T12:32:38Z" finished-at="2023-02-27T12:33:33Z">
      <class name="sample.NewTest">
        <test-method status="PASS" signature="launch()[pri:0, instance:sample.NewTest@1753acfe]" name="launch" is-config="true" duration-ms="15900" started-at="2023-02-27T12:32:38Z" finished-at="2023-02-27T12:32:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="FAIL" signature="f()[pri:0, instance:sample.NewTest@1753acfe]" name="f" duration-ms="359" started-at="2023-02-27T12:32:54Z" finished-at="2023-02-27T12:32:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ Amazon.in: : All Categories] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ Amazon.in: : All Categories] but found [Online Shopping site in India: Shop Online for Mobiles, Books, Watches, Shoes and More - Amazon.in]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at sample.NewTest.f(NewTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:sample.NewTest@1753acfe]" name="afterMethod" is-config="true" duration-ms="1072" started-at="2023-02-27T12:32:55Z" finished-at="2023-02-27T12:32:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="launch()[pri:0, instance:sample.NewTest@1753acfe]" name="launch" is-config="true" duration-ms="12479" started-at="2023-02-27T12:32:56Z" finished-at="2023-02-27T12:33:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="verfylog()[pri:0, instance:sample.NewTest@1753acfe]" name="verfylog" duration-ms="606" started-at="2023-02-27T12:33:08Z" finished-at="2023-02-27T12:33:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfylog -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:sample.NewTest@1753acfe]" name="afterMethod" is-config="true" duration-ms="2102" started-at="2023-02-27T12:33:09Z" finished-at="2023-02-27T12:33:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="launch()[pri:0, instance:sample.NewTest@1753acfe]" name="launch" is-config="true" duration-ms="10761" started-at="2023-02-27T12:33:11Z" finished-at="2023-02-27T12:33:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="autosugg()[pri:1, instance:sample.NewTest@1753acfe]" name="autosugg" duration-ms="10094" started-at="2023-02-27T12:33:22Z" finished-at="2023-02-27T12:33:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- autosugg -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:sample.NewTest@1753acfe]" name="afterMethod" is-config="true" duration-ms="822" started-at="2023-02-27T12:33:32Z" finished-at="2023-02-27T12:33:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sample.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
